### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by Apollon77**
Hi @forelleblau,

I started using the adapter and saw some issues with my modem. So I decided to have a run over the code and also cleanup some async stuff and make sure all is more executed sequencially and not that much in parallel. I hope you are ok with the changes. If you have questions just ask :-)

it works that way for me

And the good thing is ... with this version the Repo-Reveiw is also done :-)

Ingo

### CODE REVIEW

**Comment by forelleblau** [comment]
Dear Apollon77

Thanks a lot for your 'Optimizations'. Now you probably ended up with a lot of additional work with re-doing my beginners-code. But I hope everyting works fine now and the adapter will be useful for a lot of ioBroker-users.

Thank you very much

Marcel

**Comment by Apollon77** [comment]
All fine Marcel, I just reorganized some stuff :-))

**Comment by Apollon77** [comment]
Please also release it :-) I think with this you also have a good basis for the future

**Comment by forelleblau** [comment]
Dear @Apollon77 

The new code throws an error on incoming messages:

> 
gsmsms.0 | 2023-01-10 19:53:32.434 | error | Cannot read property 'sender' of undefined
-- | -- | -- | --
gsmsms.0 | 2023-01-10 19:53:32.434 | error | TypeError: Cannot read property 'sender' of undefined at EventEmitter.<anonymous> (/opt/iobroker/node_modules/iobroker.gsmsms/main.js:261:44) at EventEmitter.emit (events.js:400:28) at EventEmitter.modem.emitNewIncomingMessage (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:174:11) at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1136:21 at Immediate.<anonymous> (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:191:7) at processImmediate (internal/timers.js:466:21)
gsmsms.0 | 2023-01-10 19:53:32.430 | error | uncaught exception: Cannot read property 'sender' of undefined
gsmsms.0 | 2023-01-10 19:53:32.430 | info | Event New Message: []
gsmsms.0 | 2023-01-10 19:53:32.429 | debug | Event New Message Indication: {"status":"success","request":"readSMSById","data":[]}
gsmsms.0 | 2023-01-10 19:53:32.427 | error | Cannot read property 'udhs' of undefined
gsmsms.0 | 2023-01-10 19:53:32.426 | error | TypeError: Cannot read property 'udhs' of undefined at EventEmitter.modem.deleteMessage (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1514:46) at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1505:15 at new Promise (<anonymous>) at EventEmitter.modem.deleteMessage (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1504:14) at EventEmitter.item.logic (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:230:17) at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1205:50 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1104:16 at Array.forEach (<anonymous>) at SerialPort.modem.dataReceived (/opt/iobroker/node_modules/serialport-gsm/lib/functions/modem.js:1102:11)
gsmsms.0 | 2023-01-10 19:53:32.425 | error | unhandled promise rejection: Cannot read property 'udhs' of undefined
gsmsms.0 | 2023-01-10 19:53:32.425 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

>

As far as I could identify it's caused by serialport-gsm setting the default device stroage to 'SM' (cpms="SM) [here](https://github.com/zabsalahid/serialport-gsm/blob/master/lib/functions/modem.js#L342).

Setting the storage with a custom init command to 'SM"does not solve the problem.
It is solved (for my device) if I change the "SM" in the serialport-gsm code to "ME".  I think the storage set with the command above should be definable in the options. I will work on an PR for serialport-gsm. 

OK? Or any more appropriate suggestions?

Marcel

**Comment by forelleblau** [comment]
Solved in the second run....with correct AT+CPMS="SM","SM","SM" as customInit command it works...will set a hint in README and release it.

**Comment by Apollon77** [comment]
>  I will work on an PR for serialport-gsm.

this is the best idea I think. Thank you, juet mention me for review

**Pull request merged**
